name: differenz_e_commerce_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shimmer: 2.0.0
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  dio: ^4.0.6
  woocommerce_api: ^0.1.0
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.10
  carousel_slider: ^4.1.1
  sqflite: ^2.0.2+1
  path: ^1.8.0
  http: ^0.13.4
  fancy_shimmer_image: ^2.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter


flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/font/montserrat/Montserrat-Medium.ttf
        - asset: assets/font/montserrat/Montserrat-Regular.ttf
        - asset: assets/font/montserrat/Montserrat-Bold.ttf

    - family: CartMax
      fonts: 
        - asset: assets/font/CartMax.ttf

  uses-material-design: true

